[project]
name = "salesbrochuregenerator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "ipython>=9.8.0",
    "openai>=2.14.0",
    "requests>=2.32.5",
]
